# Generated by Django 5.1.4 on 2026-07-22 22:38

import django.db.models.deletion
from django.db import migrations, models


def backfill_inquiry_tenant(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    SaleInquiry = apps.get_model("pages", "SaleInquiry")
    default_tenant = Tenant.objects.order_by("id").first()
    if default_tenant is None:
        return
    SaleInquiry.objects.filter(tenant__isnull=True).update(tenant=default_tenant)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinquiry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_inquiries', to='tenants.tenant'),
        ),
        migrations.RunPython(backfill_inquiry_tenant, migrations.RunPython.noop),
    ]
