# Generated by Django 5.1.4 on 2026-07-08 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe', max_length=32)),
                ('plan_code', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('provider_customer_id', models.CharField(blank=True, max_length=255)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
