# Generated by Django 5.1.4 on 2026-07-22 22:38

import django.db.models.deletion
from django.db import migrations, models


def backfill_subscription_tenant(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    User = apps.get_model("accounts", "User")
    Subscription = apps.get_model("billing", "Subscription")

    default_tenant = Tenant.objects.order_by("id").first()
    if default_tenant is None:
        return

    User.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    for subscription in Subscription.objects.select_related("user").filter(tenant__isnull=True):
        subscription.tenant_id = subscription.user.tenant_id or default_tenant.id
        subscription.save(update_fields=["tenant"])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenants.tenant'),
        ),
        migrations.RunPython(backfill_subscription_tenant, migrations.RunPython.noop),
    ]
