# Generated by Django 5.1.4 on 2026-07-23 02:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscription_tenant'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status', 'updated_at'], name='billing_sub_user_id_77a47b_idx'),
        ),
    ]
