# Generated by Django 5.1.4 on 2026-07-26 13:58

import django.db.models.deletion
from django.db import migrations, models


def backfill_subscription_tenant_users(apps, schema_editor):
    Subscription = apps.get_model("billing", "Subscription")
    TenantUser = apps.get_model("tenants", "TenantUser")

    for subscription in Subscription.objects.exclude(tenant_id=None).iterator():
        subscription.tenant_user_id = (
            TenantUser.objects.filter(
                tenant_id=subscription.tenant_id,
                identity_id=subscription.user_id,
            )
            .values_list("id", flat=True)
            .first()
        )
        if subscription.tenant_user_id:
            subscription.save(update_fields=("tenant_user",))


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscription_billing_sub_user_id_77a47b_idx'),
        ('tenants', '0006_tenantuser_tenantmembership_tenant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tenant_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenants.tenantuser'),
        ),
        migrations.RunPython(backfill_subscription_tenant_users, migrations.RunPython.noop),
    ]
