# Generated by Django 5.1.4 on 2026-07-22 22:38

import django.db.models.deletion
from django.db import migrations, models


def assign_default_tenant_to_users(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    User = apps.get_model("accounts", "User")
    default_tenant = Tenant.objects.order_by("id").first()
    if default_tenant is None:
        return
    User.objects.filter(tenant__isnull=True).update(tenant=default_tenant)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_subscription_expires_at'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tenant_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenants.tenant'),
        ),
        migrations.RunPython(assign_default_tenant_to_users, migrations.RunPython.noop),
    ]
