# Generated by Django 5.1.4 on 2026-07-26 09:07

import backend.apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hide_database_google_social_apps'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', backend.apps.accounts.models.UserManager()),
            ],
        ),
    ]
