# Generated by Django 5.1.4 on 2026-07-08 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('full_test', 'Full Test'), ('section', 'Section')], max_length=24)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='created', max_length=24)),
                ('overall_adjusted_score', models.FloatField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttemptSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('reasoning', 'Reasoning'), ('perceptual_speed', 'Perceptual Speed'), ('number_speed_accuracy', 'Number Speed & Accuracy'), ('word_meaning', 'Word Meaning'), ('spatial_visualization', 'Spatial Visualization')], max_length=32)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(default='easy', max_length=16)),
                ('time_limit_seconds', models.PositiveIntegerField()),
                ('question_count', models.PositiveIntegerField(default=10)),
                ('adjusted_score', models.FloatField(default=0)),
                ('question_payload', models.JSONField(default=list)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessments.attempt')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.PositiveIntegerField()),
                ('user_answer', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('penalty_applied', models.FloatField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.attemptsection')),
            ],
        ),
    ]
