# Generated by Django 5.1.4 on 2026-07-22 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_tenant_fields(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    User = apps.get_model("accounts", "User")
    Attempt = apps.get_model("assessments", "Attempt")
    AttemptSection = apps.get_model("assessments", "AttemptSection")
    AttemptAnswer = apps.get_model("assessments", "AttemptAnswer")
    SectionProgress = apps.get_model("assessments", "SectionProgress")

    default_tenant = Tenant.objects.order_by("id").first()
    if default_tenant is None:
        return

    users_without_tenant = User.objects.filter(tenant__isnull=True)
    if users_without_tenant.exists():
        users_without_tenant.update(tenant=default_tenant)

    for attempt in Attempt.objects.select_related("user").filter(tenant__isnull=True):
        attempt.tenant_id = attempt.user.tenant_id or default_tenant.id
        attempt.save(update_fields=["tenant"])

    for section in AttemptSection.objects.select_related("attempt").filter(tenant__isnull=True):
        section.tenant_id = section.attempt.tenant_id or default_tenant.id
        section.save(update_fields=["tenant"])

    for answer in AttemptAnswer.objects.select_related("attempt_section").filter(tenant__isnull=True):
        answer.tenant_id = answer.attempt_section.tenant_id or default_tenant.id
        answer.save(update_fields=["tenant"])

    for progress in SectionProgress.objects.select_related("user").filter(tenant__isnull=True):
        progress.tenant_id = progress.user.tenant_id or default_tenant.id
        progress.save(update_fields=["tenant"])


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_alter_attemptsection_section_type_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectionprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attempt',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempt_answers', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='attemptsection',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempt_sections', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='sectionprogress',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_progress_rows', to='tenants.tenant'),
        ),
        migrations.RunPython(backfill_tenant_fields, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='sectionprogress',
            unique_together={('tenant', 'user', 'assessment_type', 'section_type')},
        ),
    ]
