# Generated by Django 5.1.4 on 2026-07-23 02:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_alter_sectionprogress_unique_together_attempt_tenant_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'mode', 'assessment_type'], name='assessments_user_id_35a4fa_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'status', 'started_at'], name='assessments_user_id_0adfd3_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptsection',
            index=models.Index(fields=['attempt', 'order_index'], name='assessments_attempt_16c307_idx'),
        ),
    ]
