# Generated by Django 5.1.4 on 2026-07-23 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_tracks(apps, schema_editor):
    AssessmentTrack = apps.get_model("assessments", "AssessmentTrack")
    Tenant = apps.get_model("tenants", "Tenant")
    default_tenant = Tenant.objects.filter(slug="mindmetric").first()

    seed_rows = [
        {
            "assessment_type": "prepgia",
            "title": "Thomas GIA",
            "description": "Thomas GIA-style speed practice with full tests and section-wise drills.",
            "module_count": 5,
            "trust_line": "Used by 30,000+ employers across the UK and Europe",
            "available_languages": ["English"],
            "visibility_state": "accessible",
        },
        {
            "assessment_type": "ccat",
            "title": "CCAT",
            "description": "Numerical, verbal, and abstract aptitude practice with module drills and full tests.",
            "module_count": 3,
            "trust_line": "Taken 10M+ times at 4,500+ US employers",
            "available_languages": ["English"],
            "visibility_state": "accessible",
        },
        {
            "assessment_type": "watson_glaser",
            "title": "Watson-Glaser",
            "description": "Critical reasoning practice covering inference, assumptions, and argument evaluation.",
            "module_count": 4,
            "trust_line": "In testing with a small group right now",
            "available_languages": ["English"],
            "visibility_state": "upcoming",
        },
        {
            "assessment_type": "shl_verify",
            "title": "SHL Verify",
            "description": "Numerical, verbal, and inductive reasoning practice in the SHL question style.",
            "module_count": 4,
            "trust_line": "In testing with a small group right now",
            "available_languages": ["English"],
            "visibility_state": "upcoming",
        },
    ]

    for row in seed_rows:
        AssessmentTrack.objects.update_or_create(
            tenant=default_tenant,
            assessment_type=row["assessment_type"],
            defaults=row,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_attempt_assessments_user_id_35a4fa_idx_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('module_count', models.PositiveIntegerField(default=0)),
                ('trust_line', models.CharField(blank=True, max_length=255)),
                ('available_languages', models.JSONField(blank=True, default=list)),
                ('visibility_state', models.CharField(choices=[('accessible', 'Accessible'), ('upcoming', 'Upcoming'), ('hidden', 'Hidden')], default='accessible', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('last_released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_tracks', to='tenants.tenant')),
            ],
            options={
                'ordering': ('title',),
                'indexes': [models.Index(fields=['tenant', 'visibility_state', 'assessment_type'], name='assessments_tenant__ec2ce6_idx')],
                'unique_together': {('tenant', 'assessment_type')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentTrackWaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('source_page', models.CharField(blank=True, max_length=64)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_track_waitlist_entries', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_track_waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'assessment_type', 'notified_at'], name='assessments_tenant__df4b6c_idx')],
                'unique_together': {('tenant', 'assessment_type', 'email')},
            },
        ),
        migrations.RunPython(seed_default_tracks, migrations.RunPython.noop),
    ]
