# Generated by Django 5.1.4 on 2026-07-26 13:58

import django.db.models.deletion
from django.db import migrations, models


def backfill_assessment_tenant_users(apps, schema_editor):
    Attempt = apps.get_model("assessments", "Attempt")
    SectionProgress = apps.get_model("assessments", "SectionProgress")
    TenantUser = apps.get_model("tenants", "TenantUser")

    def tenant_user_id(tenant_id, user_id):
        if not tenant_id:
            return None
        return (
            TenantUser.objects.filter(tenant_id=tenant_id, identity_id=user_id)
            .values_list("id", flat=True)
            .first()
        )

    for attempt in Attempt.objects.exclude(tenant_id=None).iterator():
        attempt.tenant_user_id = tenant_user_id(attempt.tenant_id, attempt.user_id)
        if attempt.tenant_user_id:
            attempt.save(update_fields=("tenant_user",))

    for progress in SectionProgress.objects.exclude(tenant_id=None).iterator():
        progress.tenant_user_id = tenant_user_id(progress.tenant_id, progress.user_id)
        if progress.tenant_user_id:
            progress.save(update_fields=("tenant_user",))


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_assessmenttrack_assessmenttrackwaitlistentry'),
        ('tenants', '0006_tenantuser_tenantmembership_tenant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='tenant_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='tenants.tenantuser'),
        ),
        migrations.AddField(
            model_name='sectionprogress',
            name='tenant_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_progress_rows', to='tenants.tenantuser'),
        ),
        migrations.RunPython(backfill_assessment_tenant_users, migrations.RunPython.noop),
    ]
