# Generated by Django 5.1.4 on 2026-08-01

import django.db.models.deletion
from django.db import migrations, models


MODULES_BY_ASSESSMENT = {
    "prepgia": (
        "reasoning",
        "perceptual_speed",
        "number_speed_accuracy",
        "word_meaning",
        "spatial_visualization",
    ),
    "ccat": (
        "ccat_numerical",
        "ccat_verbal",
        "ccat_spatial",
    ),
}


def seed_free_tier_module_limits(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    FreeTierModuleLimit = apps.get_model("assessments", "FreeTierModuleLimit")

    rows = []
    for tenant_id in Tenant.objects.values_list("id", flat=True).iterator():
        for assessment_type, section_types in MODULES_BY_ASSESSMENT.items():
            for section_type in section_types:
                rows.append(
                    FreeTierModuleLimit(
                        tenant_id=tenant_id,
                        assessment_type=assessment_type,
                        section_type=section_type,
                        practice_question_limit=10,
                        test_attempt_limit=2,
                    )
                )
    FreeTierModuleLimit.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0013_attempt_tenant_user_sectionprogress_tenant_user"),
        ("tenants", "0007_tenantenrollmentcode_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeTierModuleLimit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assessment_type", models.CharField(max_length=64)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("reasoning", "Reasoning"),
                            ("perceptual_speed", "Perceptual Speed"),
                            ("number_speed_accuracy", "Number Speed & Accuracy"),
                            ("word_meaning", "Word Meaning"),
                            ("spatial_visualization", "Spatial Visualization"),
                            ("ccat_numerical", "CCAT Math & Numerical Reasoning"),
                            ("ccat_verbal", "CCAT Verbal Reasoning"),
                            ("ccat_spatial", "CCAT Spatial & Abstract Reasoning"),
                        ],
                        max_length=32,
                    ),
                ),
                ("practice_question_limit", models.PositiveIntegerField(default=10)),
                ("test_attempt_limit", models.PositiveIntegerField(default=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="free_tier_module_limits",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("tenant", "assessment_type", "section_type"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "assessment_type", "section_type"),
                        name="unique_free_tier_module_limit",
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_free_tier_module_limits, migrations.RunPython.noop),
    ]
