# Generated by Django 5.1.4 on 2026-07-26 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def configure_existing_tenants(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    for tenant in Tenant.objects.all():
        tenant.allowed_assessments = ["prepgia", "ccat"]
        if tenant.slug == "mindmetric":
            tenant.tenant_type = "platform"
            tenant.subdomain_prefix = None
        else:
            tenant.tenant_type = "institution"
            tenant.subdomain_prefix = tenant.primary_domain.split(".", 1)[0] or tenant.slug
        tenant.save(update_fields=("allowed_assessments", "tenant_type", "subdomain_prefix"))


def reset_existing_tenant_configuration(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    Tenant.objects.update(allowed_assessments=[], tenant_type="institution", subdomain_prefix=None)


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allowed_assessments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_plan_code',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=16),
        ),
        migrations.AddField(
            model_name='tenant',
            name='enrollment_mode',
            field=models.CharField(choices=[('open', 'Open login'), ('code_required', 'Enrollment code required')], default='open', max_length=24),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subdomain_prefix',
            field=models.SlugField(blank=True, max_length=63, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(choices=[('platform', 'Platform'), ('institution', 'Institution')], default='institution', max_length=16),
        ),
        migrations.RunPython(configure_existing_tenants, reset_existing_tenant_configuration),
        migrations.CreateModel(
            name='TenantEnrollmentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('code_prefix', models.CharField(max_length=12)),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenant_enrollment_codes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_codes', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'is_active', 'expires_at'], name='tenants_ten_tenant__927b18_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('plan_code', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=16)),
                ('access_started_at', models.DateTimeField()),
                ('access_expires_at', models.DateTimeField()),
                ('enrollment_source', models.CharField(choices=[('open_login', 'Open login'), ('code', 'Enrollment code'), ('invite', 'Pre-added student'), ('admin', 'Admin')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'status', 'access_expires_at'], name='tenants_ten_tenant__da4b05_idx'), models.Index(fields=['user', 'status', 'access_expires_at'], name='tenants_ten_user_id_132402_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='unique_tenant_membership')],
            },
        ),
        migrations.CreateModel(
            name='TenantStudentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_tenant_invites', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_invites', to='tenants.tenant')),
            ],
            options={
                'ordering': ('email',),
                'indexes': [models.Index(fields=['tenant', 'email', 'is_active'], name='tenants_ten_tenant__e60ff6_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'email'), name='unique_tenant_student_invite')],
            },
        ),
    ]
