# Generated by Django 5.1.4 on 2026-07-26 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_tenant_users(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    TenantUser = apps.get_model("tenants", "TenantUser")
    TenantMembership = apps.get_model("tenants", "TenantMembership")

    for user in User.objects.exclude(tenant_id=None).iterator():
        TenantUser.objects.get_or_create(
            tenant_id=user.tenant_id,
            identity_id=user.id,
            defaults={"email": user.email.strip().lower(), "status": "active"},
        )

    for membership in TenantMembership.objects.select_related("user").iterator():
        tenant_user, _ = TenantUser.objects.get_or_create(
            tenant_id=membership.tenant_id,
            identity_id=membership.user_id,
            defaults={"email": membership.user.email.strip().lower(), "status": "active"},
        )
        membership.tenant_user_id = tenant_user.id
        membership.save(update_fields=("tenant_user",))


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_seed_demo_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to='tenants.tenant')),
            ],
            options={
                'ordering': ('tenant__name', 'email'),
            },
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='tenant_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='tenants.tenantuser'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'status', 'joined_at'], name='tenants_ten_tenant__3f85de_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'email'], name='tenants_ten_tenant__205ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['identity', 'status'], name='tenants_ten_identit_d184c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantuser',
            constraint=models.UniqueConstraint(fields=('tenant', 'identity'), name='unique_tenant_user_identity'),
        ),
        migrations.RunPython(backfill_tenant_users, migrations.RunPython.noop),
    ]
